@startuml

title __UTILS's Class Diagram__\n

  package com.inspiware.price.aggregator {
    package com.inspiware.price.aggregator.utils {
      class TestUtils {
          {static} + DATE_31_DAYS_AGO : Date
          {static} + DATE_30_DAYS_AGO : Date
          {static} + DATE_1_WEEK_AGO : Date
          {static} + DATE_1_DAY_AGO : Date
          {static} + testInstrument1 : Instrument
          {static} + testInstrument2 : Instrument
          {static} + testInstrument3 : Instrument
          {static} + testInstrument4 : Instrument
          {static} + testInstrument5 : Instrument
          {static} + vendor1 : Vendor
          {static} + vendor2 : Vendor
          {static} + vendor3 : Vendor
          {static} + testPrice1 : InstrumentPrice
          {static} + testPrice2 : InstrumentPrice
          {static} + testPrice3 : InstrumentPrice
          {static} + testPrice4 : InstrumentPrice
          {static} + testPrice5 : InstrumentPrice
          {static} + testPrice6 : InstrumentPrice
          {static} + testPrice7 : InstrumentPrice
          {static} + testPrice8 : InstrumentPrice
          {static} + testPrice9 : InstrumentPrice
          {static} + testPrice10 : InstrumentPrice
          {static} + testPrice11 : InstrumentPrice
          {static} + testPrice12 : InstrumentPrice
          {static} + testPrice13 : InstrumentPrice
          {static} + testPrice14 : InstrumentPrice
          {static} + testPrice15 : InstrumentPrice
          {static} + testPrice16 : InstrumentPrice
          {static} + testPrice17 : InstrumentPrice
          {static} + testPrice18 : InstrumentPrice
          {static} + testPrice19 : InstrumentPrice
          {static} + testPrice20 : InstrumentPrice
          {static} + testPrice21 : InstrumentPrice
          {static} + testPrice22 : InstrumentPrice
          {static} + testPrice23 : InstrumentPrice
          {static} + testPrice24 : InstrumentPrice
          {static} + getAllPrices()
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
